# permissions for end users to view korrel8rs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korrel8r-viewer-role
rules:
- apiGroups:
  - korrel8r.openshift.io
  resources:
  - korrel8rs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - korrel8r.openshift.io
  resources:
  - korrel8rs/status
  verbs:
  - get
