kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- auth_proxy_service.yaml
- auth_proxy_role.yaml
- auth_proxy_role_binding.yaml
- auth_proxy_client_clusterrole.yaml
- korrel8r_default_role_binding.yaml
