apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Observability
    containerImage: quay.io/korrel8r/operator
    description: Correlate cluster resources and observability data.
    repository: https://github.com/korrel8r/korrel8r
    support: Korrel8r Project
  name: korrel8r.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Korrel8r is a service that correlates observabililty signals in
        the cluster.
      displayName: Korrel8r
      kind: Korrel8r
      name: korrel8rs.korrel8r.openshift.io
      version: v1alpha1
  description: |
    Korrel8r helps navigate from problem symptoms to related resources and signal data that can reveal the cause.
    It can follow relationships between disjointed observability "silos" (logs, metrics, alerts and more) to bring together all the data available to solve a problem.
    This operator allows Korrel8r to be deployed as a cluster service with a REST API.
    It can be used as a back-end for data correlation by the OpenShift console and other tools.
  displayName: Korrel8r
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCEtLSBDcmVhdGVkIHdpdGggSW5rc2NhcGUgKGh0dHA6Ly93d3cuaW5rc2NhcGUub3JnLykgLS0+Cjxzdmcgd2lkdGg9IjQwIiBoZWlnaHQ9IjQwIiB2ZXJzaW9uPSIxLjEiIHZpZXdCb3g9IjAgMCAxMC41ODMgMTAuNTgzIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxnIHRyYW5zZm9ybT0ibWF0cml4KC44MTUzIDAgMCAuNzkxOTkgLS4wMzkxNDQgLjkwNjM2KSIgc3Ryb2tlPSIjM2U0ODM3IiBzdHJva2Utd2lkdGg9Ii4yNjQ1OCI+PHBhdGggZD0ibTQuNTc4MyAyLjYxNCAxLjU0NDUgMC43MTExNiIgZmlsbD0ibm9uZSIvPjxlbGxpcHNlIGN4PSIxLjkzNjciIGN5PSI1LjczMSIgcng9Ii45NDE1OSIgcnk9Ii45OTczMSIgZmlsbD0iIzBmMCIvPjxlbGxpcHNlIGN4PSIzLjc0MjkiIGN5PSIyLjIyOTMiIHJ4PSIuOTEzNTEiIHJ5PSIuOTUwMjgiIGZpbGw9IiNmMGYiLz48cGF0aCBkPSJtMi4zODgxIDQuODU1OCAwLjkyMjg5LTEuNzg5MSIgZmlsbD0ibm9uZSIvPjxlbGxpcHNlIGN4PSIzLjQyNjgiIGN5PSI5LjA4MDEiIHJ4PSIuNjc2NTIiIHJ5PSIuNzE0OTkiIGZpbGw9IiNmYzAiLz48ZWxsaXBzZSBjeD0iNS4xNTcyIiBjeT0iNi4yMDE0IiByeD0iLjgzNzMiIHJ5PSIuOTAwNjciIGZpbGw9IiNkMzVmOGQiLz48ZWxsaXBzZSBjeD0iOC4xNjc5IiBjeT0iOC42MTQ3IiByeD0iLjkwMTY4IiByeT0iMS4wMTIzIiBmaWxsPSIjMDhhIi8+PGVsbGlwc2UgY3g9IjkuOTc4NiIgY3k9IjIuNzUxNyIgcng9Ii43NjcxIiByeT0iLjc5Nzk4IiBmaWxsPSIjMGZmIi8+PGVsbGlwc2UgY3g9IjYuODU2MiIgY3k9IjMuNjYyOSIgcng9Ii44MDIxNSIgcnk9Ii44MzQ0NCIgZmlsbD0iI2ZmMCIvPjxlbGxpcHNlIGN4PSIxMS4xNzIiIGN5PSI1Ljc4NjEiIHJ4PSIuOTEwMjYiIHJ5PSIuOTM0OTQiIGZpbGw9IiNmMDAiLz48ZyBmaWxsPSJub25lIj48cGF0aCBkPSJtMi4zMzggNi42MzMxIDAuODAwODUgMS44Ii8+PHBhdGggZD0ibTIuODY5NCA1Ljg2NzIgMS40NTgxIDAuMjEyOTgiLz48cGF0aCBkPSJtMy43ODk1IDguNDc2NiAwLjkxMzA2LTEuNTE4OSIvPjxwYXRoIGQ9Im0xMC4yNjkgMy40OTAzIDAuNTYxOCAxLjQyOSIvPjxwYXRoIGQ9Im03LjYyODYgMy40Mzc1IDEuNjExNC0wLjQ3MDI1Ii8+PHBhdGggZD0ibTUuOTkyOCA2LjE0MzcgNC4yNzA2LTAuMjk0ODMiLz48cGF0aCBkPSJtNS42NDY0IDUuNDcwNCAwLjc1MTQ2LTEuMTIyOCIvPjxwYXRoIGQ9Im01LjgyODYgNi43Mzk1IDEuNjA1NSAxLjI4NyIvPjxwYXRoIGQ9Im04Ljg1ODcgNy45NjQyIDEuNjQxOS0xLjU0NjIiLz48L2c+PC9nPjwvc3ZnPgo=
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - observability
  - signal
  - correlation
  links:
  - name: Documentation
    url: https://korrel8r.github.io/korrel8r
  - name: Source Code and Issues
    url: https://github.com/korrel8r/korrel8r
  maintainers:
  - email: korrel8r@gmail.com
    name: Korrel8r Project
  maturity: alpha
  minKubeVersion: 1.23.0
  provider:
    name: Korrel8r
    url: https://github.com/korrel8r/korrel8r
  version: 0.0.0
