= Hacking on the Korrel8r Operator
include::attributes.adoc[]
== Getting Started

This project follows the Kubernetes
https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Operator pattern].

It uses https://kubernetes.io/docs/concepts/architecture/controller/[Controllers], which provide a
reconcile function responsible for synchronizing resources until the desired state is reached on the
cluster.

You’ll need a Kubernetes cluster to run against. You can use https://sigs.k8s.io/kind[KIND] to get a
local cluster for testing, or run against a remote cluster. See the
https://korrel8r.github.io/korrel8r/[Korrel8r Documentation] for more about setting up your cluster.

*Note:* Your controller will automatically use the current context in your kubeconfig file
(i.e. whatever cluster `kubectl cluster-info` shows).

== Testing the operator

Start the operator using one of the methods below, then use this script to verify it is working:

[source,sh]
----
hack/smoketest.sh
----

The script creates a `Korrel8r` resource and verifies that it responds
to REST API calls. If your operator is working correctly it should print
some messages ending with ``Success.''

You can customize your own korrel8r resource, and use a browser or REST
tools to query it.

=== Running as a local process.

You can run the controller on your own development machine, outside the
cluster. This is ideal for debugging.
. Install the CRDs into the cluster:

[source,sh]
----
make install
----

. Run the controller (this will run in the foreground, so switch to a
new terminal if you want to leave it running):

[source,sh]
----
make run
----

*NOTE:* You can also run this in one step by running: `make install run`

=== Deploying via kustomize

. Build and push your image to the location specified by `IMAGE`, which
should be a base image name with no tag:

[source,sh]
----
make image-build image-push IMAGE=<some-image>
----

. Deploy the controller to the cluster with the image specified by `IMAGE`:

[source,sh]
----
make deploy IMAGE=<some-image>
----

=== Deploy as a bundle image

. Build and push your image to the location specified by `IMAGE`, which should be a base image name with no tag.
This will create images `$(IMAGE):$(VERSION)` and `$(IMAGE)-bundle:$(VERSION)`

[source,sh]
----
make push-all IMAGE=<some-image>
----

. Run the bundle image on your cluster.

[source,sh]
----
make bundle-run IMAGE=<some-image>
----

== Cleaning up

=== Uninstall CRDs

To delete the CRDs from the cluster:

[source,sh]
----
make uninstall
----

=== Undeploy the controller

[source,sh]
----
make undeploy
----

== Debugging

The `KORREL8R_VERBOSE` environment variable to a numeric value to enable
debug logs for the operator:

. The default - some start-up messages, and a single suceess/fail
message per reconcile.
. Also list the objects modified during reconciliation.
. Also print a diff of each object modified during reconciliation.

== Modifying the API definitions

If you are editing the API definitions, generate the manifests such as
CRs or CRDs using:

[source,sh]
----
make manifests
----

*NOTE:* Run `make --help` for more information on all potential `make` targets

More information can be found via the
https://book.kubebuilder.io/introduction.html[Kubebuilder Documentation]

== License

See: https://github.com/korrel8r/korrel8r/blob/main/LICENSE
