apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
  - ../default
  - ../samples
  - ../scorecard
  - ./bases/korrel8r.clusterserviceversion.yaml

replacements:
  - source:
      name: controller-manager
      kind: Deployment
      version: v1
      group: apps
      namespace: system
      fieldPath: spec.template.spec.containers.[name=manager].image
    targets:
      - select:
          kind: ClusterServiceVersion
          name: korrel8r.v0.0.0
        fieldPaths:
          - metadata.annotations.containerImage
